<!-- begin code for etype google dfp ads -->
<script async='async' src='//www.googletagservices.com/tag/js/gpt.js'></script>
<script>
var googletag = googletag || {};
googletag.cmd = googletag.cmd || [];
googletag.cmd.push(function() {
    googletag.defineSlot('/116205717/eTypeleaderboard', [728, 90], 'div-gpt-ad-1487352373268-0').addService(googletag.pubads());
    googletag.defineSlot('/116205717/eTypesidebar', [300, 250], 'div-gpt-ad-1487352373268-1').addService(googletag.pubads());
    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
});
</script>
<!-- end code for etype google dfp ads -->
