<?php
/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function md_thenews_bl_help($path, $arg) {
  switch ($path) {
    case "admin/help#md_thenews_bl":
      return '<p>'.  t("Show Twitter block and Facebook like box block.") .'</p>';
      break;
  }
}

/**
 * Implements hook_theme().
 *
 * Defines default theme template for a list of tweets.
 */
function md_thenews_bl_theme() {
  return array(
    'md_thenews_bl_twitter_pull_listing' => array(
      'variables' => array('tweets' => NULL, 'twitkey' => NULL, 'title' => NULL, 'lazy_load' => NULL),
      'template' => 'md-thenews-bl-twitter-pull-listing',
    ),
  );
}

function md_thenews_bl_preprocess(&$variables, $hook) {
  switch($hook) {
    case 'md_thenews_bl_twitter_pull_listing':
    if (!empty($variables['tweets']) && is_array($variables['tweets'])) {
      foreach ($variables['tweets'] as $key => $tweet) {
        $tweet->time_ago = t('!time ago.', array('!time' => format_interval(time() - $tweet->timestamp)));
        $variables['tweets'][$key] = $tweet;
      }
    }
    break;
  }
}

/**
* Implements hook_block_info().
*/
function md_thenews_bl_block_info() {
  // Info for Facebook block
  $blocks['md_facebook'] = array(
    'info' => t('Facebook block'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
  );

	// Info for Flickr block
  $blocks['md_flickr'] = array(
    'info' => t('Flickr block'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

function md_thenews_bl_twitter_pull_blocks() {
  return array(
    0 => (object) array(
      'delta' => 'md_thenews_bl_0',
      'tweetkey' => '@'.theme_get_setting('twitter_user'),
      'title' => false,
      'name'  => 'Twitter block',
      'number_of_items' => theme_get_setting('twitter_num'),
      'theme_key' => 'md_thenews_bl_twitter_pull_listing',
    )
  );

}

function md_thenews_bl_block_view($delta = '') {
	switch($delta){
		case 'md_facebook':
			$block['subject'] = t('Follow Us on Facebook');
			// Get setting in theme setting
			$facebook_url = theme_get_setting('facebook_url');
			$facebook_width = theme_get_setting('facebook_width');
			$facebook_colorscheme = theme_get_setting('facebook_colorscheme');
			$facebook_face = 'false';
			$facebook_stream = 'false';
			$facebook_header = 'false';
			$facebook_bordercolor = '#315C99';
			if (theme_get_setting('facebook_face')) {$facebook_face = 'true';}
			if (theme_get_setting('facebook_stream')) {$facebook_stream = 'true';}
			if (theme_get_setting('facebook_header')) {$facebook_header = 'true';}
			if (theme_get_setting('facebook_bordercolor')) {$facebook_bordercolor = '#'.theme_get_setting('facebook_bordercolor');}

			$facebook_js = '(function(d, s, id) {
				var js, fjs = d.getElementsByTagName(s)[0];
				if (d.getElementById(id)) return;
				js = d.createElement(s); js.id = id;
				js.src = "http://connect.facebook.net/en_US/all.js#xfbml=1";
				fjs.parentNode.insertBefore(js, fjs);
				}(document, \'script\', \'facebook-jssdk\'));';
			drupal_add_js($facebook_js, 'inline');

			if ($facebook_url) {
			$block['content'] = '<div id="fb-root"></div><div class="fb-like-box" data-href="'.$facebook_url.'" data-width="'.$facebook_width.'" data-show-faces="'.$facebook_face.'" data-border-color="'.$facebook_bordercolor.'" data-stream="'.$facebook_stream.'" data-header="'.$facebook_header.'"></div>';
			} else {
				$block['content'] = 'Please go to Appearance » MD TheNews (settings) and configure at "Social Media Promotion" tab';
			}
			break;

		case 'md_flickr':
			$block['subject'] = t('Lastest Flickr');
			// Get setting in theme setting
			$flickr_id = theme_get_setting('flickr_id');
			$flickr_limit = theme_get_setting('flickr_limit');
			$template = t('<li><a href="{{image_b}}"><img src="{{image_s}}" alt="{{title}}" /></a></li>');
			$flickr_js = "jQuery(function(){
				jQuery('ul#flickrfeed').jflickrfeed({
					limit: $flickr_limit,
					qstrings: {id: '$flickr_id'},
					itemTemplate: '$template',
				});
			});";
			drupal_add_js(drupal_get_path('module', 'md_thenews_bl') . '/js/jflickrfeed.min.js');
			drupal_add_js($flickr_js, 'inline');

			$block['content'] = t('<ul id="flickrfeed" class="clearfix"></ul>');
			break;
	}

   return $block;
}