<?php
/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function mdthenews_help($path, $arg) {
  switch ($path) {
    case "admin/help#mdthenews":
      return '<p>'.  t("No help provided.") .'</p>';
      break;
  }
}
